### ISSUE TITLE
Change in araport workspace

### ISSUE THREAD

**Issue by xirdneh** [asherpasha/Araport_GeneSlider#1]
Hi,
We are going to make some changes in the araport workspace. The new changes will give more freedom to science apps deveopers. One of the changes it the way that we process app's dependencies. This will change the url from where the dependency gets pulled. Because of this we will need you to change your code in order to be compliant with this change. 
You only need to update one line in your code: https://github.com/asherpasha/Araport_GeneSlider/blob/master/app/scripts/app.js#L20 
You just have to add an 'i' at the end of the regular expression, making it case insensitive will fix any future issues.
re = /^(._)(\/geneslider_bower_package[^\/]_)\/(._)geneSlider.js??(._)?$/i

Thank you.

**Comment by asherpasha** [comment]
I will update the code.
Thanks.
